version: '3.8'

services:
  jenkins-agent-python: 
    image: jenkins-agent-python:latest
    container_name: jenkins-agent-python
    restart: unless-stopped
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=docker-agent-python
      - JENKINS_SECRET=d8a1d7d24c1b5c868712bd6a17184fd493cd28b187b889c0f261d6bbcb9bb0ae
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins: 
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - C:/docker/jenkins:/var/jenkins_home
    restart : unless-stopped
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false