services:
  jenkins-agent-python: 
    image: jenkins-agent-python:latest
    container_name: jenkins-agent-python
    restart: unless-stopped
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=docker-agent-python
      - JENKINS_SECRET=d8a1d7d24c1b5c868712bd6a17184fd493cd28b187b889c0f261d6bbcb9bb0ae
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins-test-agent: 
    image: jenkins-test-agent:latest
    container_name: jenkins-test-python
    restart: unless-stopped
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=jenkins-test-agent
      - JENKINS_SECRET=d26a4b377c3ecdd0916819ad096b20e8aa92443624d017d7f3fc04b214f2f4d4
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins: 
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - C:/docker/jenkins:/var/jenkins_home
    restart : unless-stopped
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - C:/docker/sonarqube_data:/opt/sonarqube/data
      - C:/docker/sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db
      
  sonar-db:
    image: postgres:13
    container_name: sonar-db
    volumes:
      - C:/docker/sonar-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube

#Clé sonarQube : sqp_81507600ed2166db5435443d5c8e609e6be069cf